"""Adding WardVehicles table

Revision ID: 23cc672ebe53
Revises: 99e05586eb42
Create Date: 2024-08-14 11:51:59.276011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cc672ebe53'
down_revision = '99e05586eb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_code', sa.String(length=100), nullable=False),
    sa.Column('ward_name', sa.String(length=100), nullable=False),
    sa.Column('no_cars_vans', sa.Integer(), nullable=False),
    sa.Column('one_car_van', sa.Integer(), nullable=False),
    sa.Column('two_cars_vans', sa.Integer(), nullable=False),
    sa.Column('three_or_more_cars_vans', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_availability')
    # ### end Alembic commands ###
