"""Add population columns

Revision ID: 309d103f42ae
Revises: c06c76a56d58
Create Date: 2024-08-07 10:17:22.912282

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '309d103f42ae'
down_revision = 'c06c76a56d58'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward_population', schema=None) as batch_op:
        # Add columns with default values
        batch_op.add_column(sa.Column('total_population', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('population_under_15', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('population_age_16_24', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('population_age_25_49', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('population_age_50_64', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('population_over_65', sa.Integer(), nullable=False, server_default='0'))

        # Drop the old column
        batch_op.drop_column('population')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward_population', schema=None) as batch_op:
        # Re-add the dropped column
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=False))
        
        # Drop the new columns
        batch_op.drop_column('population_over_65')
        batch_op.drop_column('population_age_50_64')
        batch_op.drop_column('population_age_25_49')
        batch_op.drop_column('population_age_16_24')
        batch_op.drop_column('population_under_15')
        batch_op.drop_column('total_population')
    # ### end Alembic commands ###
