"""Adding WardTenures table

Revision ID: 7f7fea3aba3b
Revises: 23cc672ebe53
Create Date: 2024-08-14 13:43:47.659727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7fea3aba3b'
down_revision = '23cc672ebe53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward_tenures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_code', sa.String(length=100), nullable=False),
    sa.Column('ward_name', sa.String(length=100), nullable=False),
    sa.Column('owns_outright', sa.Integer(), nullable=False),
    sa.Column('owns_with_mortgage', sa.Integer(), nullable=False),
    sa.Column('shared_ownership', sa.Integer(), nullable=False),
    sa.Column('rents_council', sa.Integer(), nullable=False),
    sa.Column('other_social_rented', sa.Integer(), nullable=False),
    sa.Column('rents_private_landlord', sa.Integer(), nullable=False),
    sa.Column('other_private_rented', sa.Integer(), nullable=False),
    sa.Column('lives_rent_free', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ward_tenures')
    # ### end Alembic commands ###
