"""Add WardGeneralHealth table

Revision ID: 8c2f3c69f58b
Revises: 309d103f42ae
Create Date: 2024-08-08 14:39:07.938024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2f3c69f58b'
down_revision = '309d103f42ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_code', sa.String(length=100), nullable=False),
    sa.Column('ward_name', sa.String(length=100), nullable=False),
    sa.Column('usual_residents', sa.Integer(), nullable=False),
    sa.Column('residentsGoodHealth', sa.Integer(), nullable=False),
    sa.Column('residentsFairHealth', sa.Integer(), nullable=False),
    sa.Column('residentsBadHealth', sa.Integer(), nullable=False),
    sa.Column('residentVeryBadHealth', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_code')
    )
    with op.batch_alter_table('ward_population', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_wardgeneralhealth_ward_code', ['ward_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ward_population', schema=None) as batch_op:
        batch_op.drop_constraint('uq_wardgeneralhealth_ward_code', type_='unique')

    op.drop_table('general_health')
    # ### end Alembic commands ###
