"""Adding WardOccupation table

Revision ID: 99e05586eb42
Revises: 8c2f3c69f58b
Create Date: 2024-08-14 10:33:05.658823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e05586eb42'
down_revision = '8c2f3c69f58b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward_occupation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_code', sa.String(length=100), nullable=False),
    sa.Column('ward_name', sa.String(length=100), nullable=False),
    sa.Column('managers_directors_senior_officials', sa.Integer(), nullable=False),
    sa.Column('professional_occupations', sa.Integer(), nullable=False),
    sa.Column('associate_professional_technical', sa.Integer(), nullable=False),
    sa.Column('administrative_secretarial', sa.Integer(), nullable=False),
    sa.Column('skilled_trades', sa.Integer(), nullable=False),
    sa.Column('caring_leisure_service', sa.Integer(), nullable=False),
    sa.Column('sales_customer_service', sa.Integer(), nullable=False),
    sa.Column('process_plant_machine_operatives', sa.Integer(), nullable=False),
    sa.Column('elementary_occupations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ward_occupation')
    # ### end Alembic commands ###
